### ISSUE TITLE
Blendshapes of the 16k vertex model produce faulty shapes

### ISSUE THREAD

**Issue by wli75** [patrikhuber/4dface#12] opened 2016-11-28 18:56 UTC
Thank you for your effort in this repo! I've learnt a lot from it.

I was wondering if the blendshape is working as intended. In addition to writing a neutral face to an .obj file, I also wanted to write a face with expression to another file.
`// neutral_expression and merged_mesh are defined in 4dface.cpp
  render::write_textured_obj(neutral_expression, "neutral.obj");
  render::write_textured_obj(merged_mesh, "expression.obj");`

The neutral face looks great, but not for the one with expression. I think it has something to do with the blendshape, but I'm not sure.
![screen shot 2016-11-29 at 2 31 42 am](https://cloud.githubusercontent.com/assets/16626035/20681401/70807a54-b5de-11e6-8c47-e18c89d5c36a.png)
![screen shot 2016-11-29 at 2 32 06 am](https://cloud.githubusercontent.com/assets/16626035/20681420/806ec72c-b5de-11e6-8685-4a6904ebdfa8.png)

**Comment by patrikhuber** [comment] 2016-11-28 20:35
Hi!

I think you have a simple mistake somewhere. You can try two things:

1) Use the new fitting function, which directly returns a mesh with the expression: [link](https://github.com/patrikhuber/eos/blob/master/examples/fit-model.cpp#L220)

2) Make sure you generate your shape correctly, like here: [link](https://github.com/patrikhuber/4dface/blob/master/apps/4dface.cpp#L269-L270).

**Comment by wli75** [comment] 2016-11-29 05:25
Ah! I think my problem was with sfm_3448_edge_topology.json, but I'm using a model with 16759 vertices. Any chance there will be a sfm_16759_edge_topology.json file?

**Comment by patrikhuber** [comment] 2016-11-30 10:48
I don't think this can be because of the edge_topology file. But maybe.

I've uploaded the files for all resolution levels to the CVSSP download folder (the one wher you got the model from). Do you still have access and can re-download?

**Comment by wli75** [comment] 2016-11-30 14:04
Yes, I've downloaded the new edge_topology file. You're right, it doesn't fix the problem, but I think it has something to do with 3448 vs 16759. When I load the 16759 morphable model, it gives me 55 principal components. Is this correct, or should it be 63 principal components?
`cout << morphable_model.get_shape_model().get_num_principal_components() << endl;`
Thank you for looking into this matter btw.

**Comment by patrikhuber** [comment] 2016-11-30 16:08
55 PC is fine. We retained 95% of the variance so all models have a slightly different number of PC, around 60 or so.

I think it's best if you proceed with the three things I outlined above. In addition if you can maybe try the code you have on the 3448 model and check whether it works or not - just to make sure there's nothing broken with the 16759 blendshapes, I don't really use the 16759 model much by myself but it should be alright.

**Comment by wli75** [comment] 2016-11-30 20:02
The 3448 model is working great, but I can't figure out why it's not working for the 16759 model.
I've attached a simple program (~100 lines) that I used for testing the models. It simply populates the shape and blendshape coefficients to some value within the range, and display the model.
If possible, could you take a quick look at it when you're free? I really appreciate it.
[4dface.cpp.zip](https://github.com/patrikhuber/4dface/files/622791/4dface.cpp.zip)

**Comment by patrikhuber** [comment] 2016-11-30 22:24
Thanks for the minimal code example! Your code looks indeed perfectly fine. I think the `expression_blendshapes_16759.bin` file might be somehow broken. I'll try to find out more. Can you work with the lower or higher resolution model for now?

**Comment by patrikhuber** [comment] 2016-12-01 00:23
Okay, I just spent the last couple of hours investigating this. It's very odd. I double-checked the code which generates the reduced blendshapes and everything else I could think of, and all looks fine. All the blendshapes are generated by the same code, and it works correctly for all other model resolution levels.

This is how neutral and added surprise expression look like, with the 29k model:
![neutral](https://cloud.githubusercontent.com/assets/4967343/20776835/ed72105e-b75a-11e6-82b0-a7ca4dc646bb.png)
![surprise](https://cloud.githubusercontent.com/assets/4967343/20776834/e8c681a2-b75a-11e6-9c79-dbfc89c9cc00.png)

And this is what happens to the 16k mesh when you add 0.2 * smile:
![mesh](https://cloud.githubusercontent.com/assets/4967343/20776847/fc7e8ab4-b75a-11e6-9e44-c259496920fd.png)

The "pyramids" seem to appear because some vertices are "stuck" in neutral and don't seem to move along with the other vertices. I inspected these vertices, and all of the ones that are "stuck" have a vertex id of above around 5000 or so. Which means the lower vertex id's might move correctly, while the higher ones don't. It's just a theory, I'm not sure about any of this. I have absolutely no clue what could cause this.

I don't think I'll have time to investigate this further in the next months, as I will be busy with a deadline. Do you have a very compelling reason why you have to use the 16k model and can't use the 29k or 3448 model? Or do you feel like having a look at this problem by yourself?

**Comment by wli75** [comment] 2016-12-01 08:40
No problem, I'll use the 3448 model for now. Also, will there be a expression_blendshapes_29587.bin file? The max resolution for the blendshapes right now is 16759. Thanks again for looking into the issue.

**Comment by Larumbergera** [comment] 2016-12-01 08:51
[https://github.com/patrikhuber/4dface/issues/8#issuecomment-250002267](url)

2016-12-01 9:40 GMT+01:00 wli75 <notifications@github.com>:

**Comment by patrikhuber** [comment] 2016-12-01 17:31
@wli75: I think you deleted your post, at least I got an email but can't find it posted here :-)

Great that you can use the 3448 or 29k model for now - and I suppose you found the blendshapes as well (I've renamed them now actually).

Hope we can get to the bottom of this issue with the 16k blendshapes at some point.

**Comment by wli75** [comment] 2016-12-02 06:50
Yes, I found the 29k model after I've posted my previous comment, and then I frantically deleted it.
But thank you @Larumbergera for following up.
And thank you again @patrikhuber for the repo!

**Comment by patrikhuber** [comment] 2018-01-10 10:26
Hey @wpk-,

Aah, excellent find, nice! I think that must be the cause for these issues then.
I am pretty sure that the author of [Resolution-Aware 3D Morphable Model](http://www.bmva.org/bmvc/2012/BMVC/paper109/paper109.pdf) told me that all lower resolution model vertices are subsets of the larger models. The registration algorithm also works this way, and the paper describes that in each level, the current mesh topology is upsampled with the 4-8 mesh subdivision algorithm (which would keep existing vertices and add new ones). So it's weird that the 16k model suddenly contains "new" vertices which are not a superset of lower levels.
We also wrote this down in our VISAPP paper and none of the co-authors ever hinted that this may be wrong for some models (it luckily only seems to affect the 16k model), so I am quite surprised by this discovery.

I'll send you the blendshapes training script.
Do you know how the 16k vertices are set up, are they a subset of the 29k, just in a different order, or completely different points?

Cheers!

**Comment by wpk-** [comment] 2018-01-10 10:39
It's quite subtle. The model is upsampled with said algorithm and a given threshold on the maximum triangle size (2 squared mm for the 29k model). Lower resolutions are created by setting the threshold higher. Intuitively you'd think this leaves you with a mesh that is at an "intermediate" resolution. However, because with the higher threshold some triangles are now not subdivided, the vertex order cannot be maintained.

The first 3448 triangles are created not with a threshold but with a fixed number of iterations that subdivide *all* triangles, so vertex order is maintained.

This is, by the way, also true for the 16k and 29k models: the first 3448 vertices are the same. Because eos can run on 3448 model, I'd hope that it will run fine with the 16k model, too. Just need to adapt the blendshapes.

**Comment by patrikhuber** [comment] 2018-01-10 10:52
Ah, I see! Cool! Thank you very much for that explanation! :-)

Yes, once we've got the correct blendshapes for the 16k model, everything should work just fine.

**Comment by wpk-** [comment] 2018-01-18 15:32
The blendshape file for the 16k model (`expression_blendshapes_16759.bin`) has been updated on the University of Surrey licence server. This should fix the issue.

@patrikhuber feel free to close this issue.

**Comment by patrikhuber** [comment] 2018-01-18 19:55
Thank you @wpk-! This is awesome.

**Closed by patrikhuber** 2018-01-18 19:55 UTC
Labels: bug
